config/routes.rb
AboutMe::Application.routes.draw do
  resources :contact_mes

  resources :current_projects

  resources :work_experiences

  resources :bios

end

app/models/bio.rb
class Bio < ActiveRecord::Base
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :set_bio, only: [:show, :edit, :update, :destroy]

  # GET /bios
  # GET /bios.json
  def index
    @bios = Bio.all
  end

  # GET /bios/1
  # GET /bios/1.json
  def show
  end

  # GET /bios/new
  def new
    @bio = Bio.new
  end

  # GET /bios/1/edit
  def edit
  end

  # POST /bios
  # POST /bios.json
  def create
    @bio = Bio.new(bio_params)

    respond_to do |format|
      if @bio.save
        format.html { redirect_to @bio, notice: 'Bio was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bio }
      else
        format.html { render action: 'new' }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bios/1
  # PATCH/PUT /bios/1.json
  def update
    respond_to do |format|
      if @bio.update(bio_params)
        format.html { redirect_to @bio, notice: 'Bio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bios/1
  # DELETE /bios/1.json
  def destroy
    @bio.destroy
    respond_to do |format|
      format.html { redirect_to bios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bio
      @bio = Bio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bio_params
      params.require(:bio).permit(:title, :body)
    end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/views/bios/_form.html.erb
<%= form_for(@bio) do |f| %>
  <% if @bio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bio.errors.count, "error") %> prohibited this bio from being saved:</h2>

      <ul>
      <% @bio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bios/edit.html.erb
<h1>Editing bio</h1>

<%= render 'form' %>

<%= link_to 'Show', @bio %> |
<%= link_to 'Back', bios_path %>

app/views/bios/index.html.erb
<h1>Listing bios</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bios.each do |bio| %>
      <tr>
        <td><%= bio.title %></td>
        <td><%= bio.body %></td>
        <td><%= link_to 'Show', bio %></td>
        <td><%= link_to 'Edit', edit_bio_path(bio) %></td>
        <td><%= link_to 'Destroy', bio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bio', new_bio_path %>

app/views/bios/new.html.erb
<h1>New bio</h1>

<%= render 'form' %>

<%= link_to 'Back', bios_path %>

app/views/bios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bio.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @bio.body %>
</p>

<%= link_to 'Edit', edit_bio_path(@bio) %> |
<%= link_to 'Back', bios_path %>