config/routes.rb
AboutMe::Application.routes.draw do
  resources :contact_mes

  resources :current_projects

  resources :work_experiences

  resources :bios

end

app/models/contact_me.rb
class ContactMe < ActiveRecord::Base
end

app/controllers/contact_mes_controller.rb
class ContactMesController < ApplicationController
  before_action :set_contact_me, only: [:show, :edit, :update, :destroy]

  # GET /contact_mes
  # GET /contact_mes.json
  def index
    @contact_mes = ContactMe.all
  end

  # GET /contact_mes/1
  # GET /contact_mes/1.json
  def show
  end

  # GET /contact_mes/new
  def new
    @contact_me = ContactMe.new
  end

  # GET /contact_mes/1/edit
  def edit
  end

  # POST /contact_mes
  # POST /contact_mes.json
  def create
    @contact_me = ContactMe.new(contact_me_params)

    respond_to do |format|
      if @contact_me.save
        format.html { redirect_to @contact_me, notice: 'Contact me was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_me }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_mes/1
  # PATCH/PUT /contact_mes/1.json
  def update
    respond_to do |format|
      if @contact_me.update(contact_me_params)
        format.html { redirect_to @contact_me, notice: 'Contact me was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_mes/1
  # DELETE /contact_mes/1.json
  def destroy
    @contact_me.destroy
    respond_to do |format|
      format.html { redirect_to contact_mes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_me
      @contact_me = ContactMe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_me_params
      params[:contact_me]
    end
end

app/helpers/contact_mes_helper.rb
module ContactMesHelper
end

app/views/contact_mes/_form.html.erb
<%= form_for(@contact_me) do |f| %>
  <% if @contact_me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_me.errors.count, "error") %> prohibited this contact_me from being saved:</h2>

      <ul>
      <% @contact_me.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_mes/edit.html.erb
<h1>Editing contact_me</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_me %> |
<%= link_to 'Back', contact_mes_path %>

app/views/contact_mes/index.html.erb
<h1>Listing contact_mes</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_mes.each do |contact_me| %>
      <tr>
        <td><%= link_to 'Show', contact_me %></td>
        <td><%= link_to 'Edit', edit_contact_me_path(contact_me) %></td>
        <td><%= link_to 'Destroy', contact_me, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact me', new_contact_me_path %>

app/views/contact_mes/new.html.erb
<h1>New contact_me</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_mes_path %>

app/views/contact_mes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_me_path(@contact_me) %> |
<%= link_to 'Back', contact_mes_path %>