config/routes.rb
AboutMe::Application.routes.draw do
  resources :contact_mes

  resources :current_projects

  resources :work_experiences

  resources :bios

end

app/models/work_experience.rb
class WorkExperience < ActiveRecord::Base
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  # GET /work_experiences
  # GET /work_experiences.json
  def index
    @work_experiences = WorkExperience.all
  end

  # GET /work_experiences/1
  # GET /work_experiences/1.json
  def show
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
  end

  # POST /work_experiences
  # POST /work_experiences.json
  def create
    @work_experience = WorkExperience.new(work_experience_params)

    respond_to do |format|
      if @work_experience.save
        format.html { redirect_to @work_experience, notice: 'Work experience was successfully created.' }
        format.json { render action: 'show', status: :created, location: @work_experience }
      else
        format.html { render action: 'new' }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_experiences/1
  # PATCH/PUT /work_experiences/1.json
  def update
    respond_to do |format|
      if @work_experience.update(work_experience_params)
        format.html { redirect_to @work_experience, notice: 'Work experience was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_experiences/1
  # DELETE /work_experiences/1.json
  def destroy
    @work_experience.destroy
    respond_to do |format|
      format.html { redirect_to work_experiences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_experience_params
      params.require(:work_experience).permit(:company, :startdate, :enddate, :description)
    end
end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/work_experiences/_form.html.erb
<%= form_for(@work_experience) do |f| %>
  <% if @work_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_experience.errors.count, "error") %> prohibited this work_experience from being saved:</h2>

      <ul>
      <% @work_experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.text_field :enddate %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_experiences/edit.html.erb
<h1>Editing work_experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_experience %> |
<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/index.html.erb
<h1>Listing work_experiences</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @work_experiences.each do |work_experience| %>
      <tr>
        <td><%= work_experience.company %></td>
        <td><%= work_experience.startdate %></td>
        <td><%= work_experience.enddate %></td>
        <td><%= work_experience.description %></td>
        <td><%= link_to 'Show', work_experience %></td>
        <td><%= link_to 'Edit', edit_work_experience_path(work_experience) %></td>
        <td><%= link_to 'Destroy', work_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work experience', new_work_experience_path %>

app/views/work_experiences/new.html.erb
<h1>New work_experience</h1>

<%= render 'form' %>

<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @work_experience.company %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @work_experience.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @work_experience.enddate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_experience.description %>
</p>

<%= link_to 'Edit', edit_work_experience_path(@work_experience) %> |
<%= link_to 'Back', work_experiences_path %>