config/routes.rb
AboutMe::Application.routes.draw do
  resources :contact_mes

  resources :current_projects

  resources :work_experiences

  resources :bios

end

app/models/current_project.rb
class CurrentProject < ActiveRecord::Base
end

app/controllers/current_projects_controller.rb
class CurrentProjectsController < ApplicationController
  before_action :set_current_project, only: [:show, :edit, :update, :destroy]

  # GET /current_projects
  # GET /current_projects.json
  def index
    @current_projects = CurrentProject.all
  end

  # GET /current_projects/1
  # GET /current_projects/1.json
  def show
  end

  # GET /current_projects/new
  def new
    @current_project = CurrentProject.new
  end

  # GET /current_projects/1/edit
  def edit
  end

  # POST /current_projects
  # POST /current_projects.json
  def create
    @current_project = CurrentProject.new(current_project_params)

    respond_to do |format|
      if @current_project.save
        format.html { redirect_to @current_project, notice: 'Current project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @current_project }
      else
        format.html { render action: 'new' }
        format.json { render json: @current_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_projects/1
  # PATCH/PUT /current_projects/1.json
  def update
    respond_to do |format|
      if @current_project.update(current_project_params)
        format.html { redirect_to @current_project, notice: 'Current project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @current_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_projects/1
  # DELETE /current_projects/1.json
  def destroy
    @current_project.destroy
    respond_to do |format|
      format.html { redirect_to current_projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_project
      @current_project = CurrentProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_project_params
      params.require(:current_project).permit(:title, :description)
    end
end

app/helpers/current_projects_helper.rb
module CurrentProjectsHelper
end

app/views/current_projects/_form.html.erb
<%= form_for(@current_project) do |f| %>
  <% if @current_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_project.errors.count, "error") %> prohibited this current_project from being saved:</h2>

      <ul>
      <% @current_project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/current_projects/edit.html.erb
<h1>Editing current_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_project %> |
<%= link_to 'Back', current_projects_path %>

app/views/current_projects/index.html.erb
<h1>Listing current_projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @current_projects.each do |current_project| %>
      <tr>
        <td><%= current_project.title %></td>
        <td><%= current_project.description %></td>
        <td><%= link_to 'Show', current_project %></td>
        <td><%= link_to 'Edit', edit_current_project_path(current_project) %></td>
        <td><%= link_to 'Destroy', current_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Current project', new_current_project_path %>

app/views/current_projects/new.html.erb
<h1>New current_project</h1>

<%= render 'form' %>

<%= link_to 'Back', current_projects_path %>

app/views/current_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @current_project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @current_project.description %>
</p>

<%= link_to 'Edit', edit_current_project_path(@current_project) %> |
<%= link_to 'Back', current_projects_path %>